spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      clientName: potm-svc
      database: 0
      timeout: 6000  # 连接超时时长（毫秒）
      jedis:
        pool:
          max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 5      # 连接池中的最大空闲连接
          min-idle: 2

  datasource:
    dynamic:
      primary: mysql-ds
      strict: true
      datasource:
        mysql-ds:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/potm_svc?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          username: root
          password: 123456
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 300000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      validation-timeout: 3000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      connection-init-sql: SET NAMES utf8mb4
      keepalive-time: 60000

plugins:
  storage:
    enable: true
    store-type: fs
    fs:
      root-path: C:\uploads
